# Generated by Django 4.0.3 on 2022-03-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_category_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='likes',
        ),
    ]
